### ISSUE TITLE
Support for PulseAudio

### ISSUE THREAD

**Issue by ssfrr** [JuliaAudio/PortAudio.jl#42]
See #40 for some more context, but I figured it would be good to track this in a separate issue.

Currently PortAudio fails to load any plugins, which means it can't access PulseAudio devices.

I think we'll need to add the `alsa-plugins` tarball to the `alsa_jll` builder and bundle them together. I have a feeling this will require getting `libpulse` to build as well. This still leaves the question of how to get ALSA to look in the right place at runtime - apparently the library search path is set at build time (I believe with the `--with-plugindir` configure option). There's some more info and even a patch for ALSA [here](https://github.com/NixOS/nixpkgs/issues/6860). A [comment](https://github.com/NixOS/nixpkgs/issues/6860#issuecomment-471394001) seems to indicate that we may be able to set the plugin path in a config file - so maybe we can bundle the config as well, we just need to get ALSA to load _that_.

It looks like as of 2013 (version 1.0.27.1) they set ALSA to stop searching `ld.so.conf` directories and instead rely on `ALSA_PLUGIN_DIR`. Bummer.

It [looks like the snap folks may have a solution](https://forum.snapcraft.io/t/reusable-alsa-lib-part/3556). This approach seems to completely ignore the system configuration and sets things up to route all ALSA sound through pulseaudio rather than exposing any direct ALSA hardware. I don't think that's the way to go for PortAudio.jl, but at least might have some good examples of how to configure things. There's an overview of the ALSA config system [here](https://www.alsa-project.org/main/index.php/Asoundrc)

So I think these are the steps to resolve this:

- [ ] Get [alsa-plugins](https://alsa-project.org/wiki/Main_Page) building as part of `alsa_jll`
- [ ] See if `--with-plugindir` will take a relative path (to find the plugins relative to `libasound.so`
- [ ] if that doesn't work, review the config docs and try including a config file that will set the plugin paths at runtime. This could either be in `__init__()` or a `build.jl` so it just happens once

**Comment by bramtayl** [comment]
@ssfrr I had a go at this. It looks like to get the PulseAudio plug-in from ALSA plugins, you do indeed need libpulseaudio. I tried installing PulseAudio, which has a metric ton of dependencies. I've got some of them built: JSON_C_jll, SpeexDSP_jll, and Libtool_jll. But now I'm stuck. Below are various avenues I've pursued:

1) libatomic_ops is listed as a dependency of PulseAudio, but I can't get it to build. `./configure` + `make` + `make install` seems to work just fine, but doesn't result in a binary. I'm not even sure if these is a binary, and I'm also not sure if it's even necessary because newer versions of C come with atomics?

2) Building PulseAudio I run into the following two problems. 
2a) I'm not sure if we need any of the optional dependencies for PulseAudio? I had to explicitly disable capabilities support, so I'm guessing that libcap might be an important one?
2b) I'm getting a very loud warning about not being built with udev support. Looks like udev comes with systemd. I tried building a binary of systemd but I'm getting a warning about an old version of `ln` not supporting the relative flag. I wonder if BinaryBuilder is using old software?
2c) Two of the suggested configure flags, `udev-rules-dir` and `with-systemduserunitdir`, point to places that don't seem to exist. Might be related to 2b?
2c) BinaryBuilder quashes the build because PulseAudio apparently uses an unsafe flag: one of `-Ofast, -ffast-math, -funsafe-math-optimizations`. I'm not sure how to disable them, or even if it would be ok to disable them.

For reference, I'm looking at the dependencies here: https://www.freedesktop.org/wiki/Software/PulseAudio/Download/ and build instructions here: https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/PulseAudioFromGit/

**Comment by bramtayl** [comment]
Updates, I'm sorting out some problems with binary builder, and have got a whole bunch of optional dependencies built both for PulseAudio and Jack2. These libraries seem to be pretty good at finding each other if they're available, so I don' forsee huge problems getting them to work together.

**Comment by bramtayl** [comment]
Updates: `PulseAudio_jll` and `alsa_plugins_jll` are up and running! So hopefully that should check off box 1!

**Comment by ssfrr** [comment]
great news - I think that's (hopefully?) the hardest part. Were you able to get pulseaudio devices to show up with PulseAudio.jl and the new JLLs?

**Comment by bramtayl** [comment]
Closed by #70
