### ISSUE TITLE
Building the shim library?

### ISSUE THREAD

**Issue by OliverEvans96** [JuliaAudio/PortAudio.jl#48]
Hi there,

I just noticed [this section](https://github.com/JuliaAudio/PortAudio.jl#building-the-shim-library) in README.md talking about the shim library, but there's no `deps/src` directory to be found. Just wondering if this is still necessary? If not, I'm curious how else you're handling callbacks from other threads.

Thanks!
Oliver

**Comment by ssfrr** [comment]
Whoops, that's outdated. Maintaining the callback functionality was proving troublesome so I switched to using PortAudio's blocking read/write API instead.

The code that handles that is [here](https://github.com/JuliaAudio/PortAudio.jl/blob/master/src/PortAudio.jl#L301-L340)

I just edited the README to remove that - thanks for taking a look!

**Comment by OliverEvans96** [comment]
Thanks - I've had the crazy idea to try writing an LV2 plugin in Julia, so I may try some of the callback stuff you're referring to, which it seems you described in brief [here](https://discourse.julialang.org/t/callback-thread-safety-in-0-6/1291/4). I was considering just using one of these JuliaAudio packages instead, but the plugin I want to write required MIDI, so it sounds like I'm back to plan A.

Do you happen to know why callbacks from other threads don't work? I've seen it stated several times in the docs and by Yichao, but I've yet to see an explanation of why calling a julia function from the thread that called `jl_init` is any different than calling a julia function from another thread. Is there some thread-private memory involved? Not expecting you to be the expert here, of course, just curious if you have any hints.

**Comment by ssfrr** [comment]
It's been a while since I've looked into it and in the mean-time Julia's threading has advanced significantly, so I'm not exactly sure. As I recall there are parts of the Julia runtime that are not thread-safe, so if you try to call those functions from multiple threads things can blow up.

Now that you can run code on a separate thread with `@spawn` etc. I'm not sure if this is still the case, though it's possible that `@spawn` does some bookkeeping that specifically protects against it.

It definitely used to be that doing anything that touched the GC was unsafe from a separate thread, so for a while I maintained a pure-julia callback that had a unit test that verified that `@allocated` gave `0`, but that was a real pain to keep running, and would often segfault if I made a mistake. So then I switched to writing the callback in C and exchanging data with Julia using a lock-free ringbuffer. That worked OK but was pretty complicated, and making sure it was built properly on all platforms was a hassle.

**Comment by ssfrr** [comment]
BTW the other thing with doing real-time audio in Julia is that the GC and JIT compilation can be a problem, so you'll want to pre-allocate and re-use as many buffers as you can to avoid allocation, and make sure to precompile any of the functions that get called in the render callback.

If you end up getting a build working that you can package up as a C-callable `.so` file I'd love to see it - I've had something similar in mind for a while also, but haven't had the time to dig into it.

**Comment by OliverEvans96** [comment]
Thanks for the thoughts - I think I should ask about this on discourse. I don't have the callback from another thread working yet, but I am able to get as far as loading the `.so` from an LV2 host and doing a `println` from julia right after calling `jl_init`. 

Here's the [repo](https://github.com/OliverEvans96/julia-embed-example) and [discussion](https://discourse.julialang.org/t/embedding-julia-without-rtld-global-in-dlopen/37655) from today that shows the basic idea so far. Basically, it's just a thin C wrapper that embeds julia. From there, you can load a local julia module and run your custom functions, though that isn't in my MWE.

 I'll definitely keep you updated on my progress, and possibly ask for more advice :)
