### ISSUE TITLE
Capturing stderr

### ISSUE THREAD

**Issue by petres** [JuliaAudio/PortAudio.jl#85]
Is it necessary to capture `stderr`. It makes it hard to work with the REPL in VS Code:

https://github.com/julia-vscode/julia-vscode/issues/2392

Thanks!

**Comment by ssfrr** [comment]
the underlying portaudio library dumps error messages straight to stdout/stderr, which is pretty annoying.

Given that we're now building our own portaudio binary anyways, probably the right fix is to patch portaudio to call some error callback and supply the error message, rather than printing directly.

**Comment by rob-luke** [comment]
Makes sense, @petres are you able to open a PR to address this?

**Comment by ssfrr** [comment]
portaudio is built as part of Julia's binary repository. The script is here:

https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/libportaudio/build_tarballs.jl

If you look at [line 35](https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/libportaudio/build_tarballs.jl#L35) you can see where the script applies a patch, this would be another similar patch.

**Comment by petres** [comment]
That's also upstream an issue: https://github.com/PortAudio/portaudio/issues/423 https://github.com/PortAudio/portaudio/issues/555 https://github.com/PortAudio/portaudio/issues/163
Pending 10 years, I can't afford going deeper in that. Closing it here.
