### ISSUE TITLE
Unable to install PortAudio on Julia 1.7 ARM64 on Apple M1 MacBook Pro

### ISSUE THREAD

**Issue by abhayap** [JuliaAudio/PortAudio.jl#97]
I get the following error message when I try to install PortAudio on Julia 1.7 on Apple M1 MacBook Pro using the ARM64 compile of Julia:

```
[ Info: Precompiling PortAudio [80ea8bcb-4634-5cb3-8ee8-a132660d1d2d]
ERROR: LoadError: UndefVarError: libportaudio not defined
Stacktrace:
 [1] include
   @ ./Base.jl:418 [inlined]
 [2] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1318
 [3] top-level scope
   @ none:1
 [4] eval
   @ ./boot.jl:373 [inlined]
 [5] eval(x::Expr)
   @ Base.MainInclude ./client.jl:453
 [6] top-level scope
   @ none:1
in expression starting at /Users/aparthy/.julia/packages/PortAudio/iJ74y/src/PortAudio.jl:1
ERROR: Failed to precompile PortAudio [80ea8bcb-4634-5cb3-8ee8-a132660d1d2d] to /Users/aparthy/.julia/compiled/v1.7/PortAudio/jl_UhuvQx.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
    @ Base ./loading.jl:1466
  [3] compilecache(pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1410
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1120
  [5] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1013
  [6] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:997
  [7] eval
    @ ./boot.jl:373 [inlined]
  [8] eval
    @ ./Base.jl:68 [inlined]
  [9] repleval(m::Module, code::Expr, #unused#::String)
    @ VSCodeServer ~/.vscode-oss/extensions/julialang.language-julia-1.5.8/scripts/packages/VSCodeServer/src/repl.jl:157
 [10] (::VSCodeServer.var"#71#73"{Module, Expr, REPL.LineEditREPL, REPL.LineEdit.Prompt})()
    @ VSCodeServer ~/.vscode-oss/extensions/julialang.language-julia-1.5.8/scripts/packages/VSCodeServer/src/repl.jl:123
 [11] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging ./logging.jl:511
 [12] with_logger
    @ ./logging.jl:623 [inlined]
 [13] (::VSCodeServer.var"#70#72"{Module, Expr, REPL.LineEditREPL, REPL.LineEdit.Prompt})()
    @ VSCodeServer ~/.vscode-oss/extensions/julialang.language-julia-1.5.8/scripts/packages/VSCodeServer/src/repl.jl:124
 [14] #invokelatest#2
    @ ./essentials.jl:716 [inlined]
 [15] invokelatest(::Any)
    @ Base ./essentials.jl:714
 [16] macro expansion
    @ ~/.vscode-oss/extensions/julialang.language-julia-1.5.8/scripts/packages/VSCodeServer/src/eval.jl:34 [inlined]
 [17] (::VSCodeServer.var"#55#56")()
    @ VSCodeServer ./task.jl:423
```

**Comment by ATell-SoundTheory** [comment]
The auto-generated wrapper [libportaudio_jll](https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl) does not export the symbol `libportaudio`, which is the name of the dynamic library for the platform. It appears that libportaudio_jll needs to be updated for Apple's aarch64 as this architecture is missing from the supported architectures.

**Comment by abhayap** [comment]
That makes sense. How can that be done?

**Comment by ATell-SoundTheory** [comment]
This should be taken care of automatically by Yggdrasil, but I think the Apple arm tooling is not yet fully available so that automatic builds for this platform are not happening. I'm sure the issue is known and being worked on. I would recommend you resort to Julia under Rosetta for the moment unless you would like to invest some time in building libportaudio_jll using the portaudio sources and BinaryBuilder.jl on your M1 Mac. A good starting point would be the libportaudio build script in the Yggdrasil github repo.

**Comment by abhayap** [comment]
Thanks! I was able to install libportaudio compiled for M1 using home-brew. Is there a way I can have Julia point to that?

**Comment by ATell-SoundTheory** [comment]
Libportaudio_jll does two things: First, it manages the artefacts, i.e. installing the required dynamic libraries. Second, it provides a julia interface to the dynamic library. Installing the dylib with homebrew takes care of the first part, but you'll have to fill in the second part. I'm not sure if homebrew is making this any easier, because BinaryBuilder.jl does both and takes care of all the little details. Building libportaudio from source is not a big deal. If you have the xcode or homebrew llvm compiler toolchain already installed then it should be as simple as running configure and then make. BinaryBuilder.jl does the same, but also takes the header file and builds your libportaudio_jll for you. This is the way I would go.

**Comment by abhayap** [comment]
Thanks for your help @ATell-SoundTheory. I got it working here: https://github.com/abhayap/libportaudio_jll

**Comment by bramtayl** [comment]
Glad you got it figured out. Seems like @ATell-SoundTheory knows more about this than me, but maybe you could make a PR to Yggrasil with fixes so other people could use it?

**Comment by abhayap** [comment]
I sent a PR here: https://github.com/JuliaPackaging/Yggdrasil/pull/4158. It's compiling on every platform including MacOS M1 except for windows. I can merge once that issue is resolved.

**Comment by abhayap** [comment]
https://github.com/PortAudio/portaudio/issues/685

**Comment by abhayap** [comment]
This is fixed by the above PR so I am closing this.
